spring:
  application:
    name: item-catalog-service

server:
  port : 8002
  #servlet:
     #context-path: /item-catalog-service
  
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
     defaultZone: http://localhost:8001/eureka
